version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: uswds
    versions:
    - 2.10.1
    - 2.10.2
    - 2.10.3
